services:
  mongo:
    image: mongo:7
    container_name: antigravity-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: antigravity-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_BACKEND_URL: http://54.242.48.48:8000
    container_name: antigravity-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo_data:
