export const KB_ADMIN = {
        loginEmailInput: 'kb-admin-login-email-input',
        loginPasswordInput: 'kb-admin-login-password-input',
        loginSubmitButton: 'kb-admin-login-submit-button',
        loginError: 'kb-admin-login-error',
        addButton: 'kb-admin-add-button',
        row: (i) => `kb-admin-row-${i}`,
        editButton: (i) => `kb-admin-edit-button-${i}`,
        deleteButton: (i) => `kb-admin-delete-button-${i}`,
        activeSwitch: (i) => `kb-admin-active-switch-${i}`,
        dialog: 'kb-admin-dialog',
        questionInput: 'kb-admin-question-input',
        answerInput: 'kb-admin-answer-input',
        categoryInput: 'kb-admin-category-input',
        saveButton: 'kb-admin-save-button',
        cancelButton: 'kb-admin-cancel-button',
        logsTab: 'kb-admin-logs-tab',
        kbTab: 'kb-admin-kb-tab',
        logRow: (i) => `kb-admin-log-row-${i}`,
        logoutButton: 'kb-admin-logout-button',
};
